// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE8xh0t9L55h5MfX0YTUlQ2BUyT_VntgE',
    appId: '1:935489326981:web:3040c6c7c24e71cd8d7eec',
    messagingSenderId: '935489326981',
    projectId: 'fintrack-7d0fc',
    authDomain: 'fintrack-7d0fc.firebaseapp.com',
    storageBucket: 'fintrack-7d0fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxC0lnBBoqBbol5p6oLAvnffUErfQUJ4Q',
    appId: '1:935489326981:android:c16de04e9272b7f68d7eec',
    messagingSenderId: '935489326981',
    projectId: 'fintrack-7d0fc',
    storageBucket: 'fintrack-7d0fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWzHbW11CQ0-BBcfcLvWo1Y0Ts61ktmLc',
    appId: '1:935489326981:ios:98171f6fe69ff3db8d7eec',
    messagingSenderId: '935489326981',
    projectId: 'fintrack-7d0fc',
    storageBucket: 'fintrack-7d0fc.firebasestorage.app',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWzHbW11CQ0-BBcfcLvWo1Y0Ts61ktmLc',
    appId: '1:935489326981:ios:98171f6fe69ff3db8d7eec',
    messagingSenderId: '935489326981',
    projectId: 'fintrack-7d0fc',
    storageBucket: 'fintrack-7d0fc.firebasestorage.app',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE8xh0t9L55h5MfX0YTUlQ2BUyT_VntgE',
    appId: '1:935489326981:web:13de0158f0a191d18d7eec',
    messagingSenderId: '935489326981',
    projectId: 'fintrack-7d0fc',
    authDomain: 'fintrack-7d0fc.firebaseapp.com',
    storageBucket: 'fintrack-7d0fc.firebasestorage.app',
  );
}
